### PR TITLE
Add service monitor to cert-exporter

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards https://github.com/giantswarm/giantswarm/issues/27576

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Tested on Gauss and on a managed EKS cluster on grizzly:

image


What's left is to test it on an AWS WC with cilium

**Comment by QuentinBisson** [comment]
Tested on 19.1.0 
image

**Comment by QuentinBisson** [comment]
@giantswarm/team-turtles could i have some eyes here?

**Comment by QuentinBisson** [comment]
As a bonus, tests are fixed

**Comment by QuentinBisson** [comment]
With proper relabelings:
image

**Review by nprokopic — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Thanks @nprokopic

**Pull request merged**
